name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: list command
        run: | 
          ls -al
          pwd
          sudo touch /home/sree.txt
          sudo echo sree is here > /home/sree.txt
          cat /home/sree.txt