name: Actions workflow

on: [push]

jobs:

  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: shrikar444/this_is_final/.github/workflows@master
        with: 
          who-to-greet: Sree