name: run multiple commands
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
           pwd
           ls -a
      - name : checkout 
        uses: actions/checkout@v1
      - name: List files after checkout 
        run: |
           pwd
           ls -a
      - name: Test connectivity
        run: echo "Hello Dear!! :)"
      - name: list command
        run: | 
          ls -al
          pwd
          sudo touch /home/sree.txt
          sudo echo sree is here > /home/sree.txt
          cat /home/sree.txt
      - name: End job
        run: echo  "End of the job" 