name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: list command
        run: | 
          ls -al
          pwd
          touch /root/sree.txt
          echo sree is here > /root/sree.txt