name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest 
    steps:
      - name: echo a string 
        run: echo "Hello this is srikar"
      - name: mutiple script 
        run: |  
          node -v
          npm -v 
      - name: python command
        run: | 
          import platform 
          print
          (platform.processor())
        shell: python
      - name: echo a string
        run: echo "Hi! Tower is working"
        run: |
         java -v
         git -v
          
